### ISSUE TITLE
`accept` in `ast.dart` crashes when children is null

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/markdown#181]
The `flutter_markdown` package uses the `markdown` package. If you try to do an image in flutter_markown, `Element.accept` in `ast.dart` crashes:

```
I/flutter (32119): When the exception was thrown, this was the stack:
I/flutter (32119): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (32119): #1      Element.accept (package:markdown/src/ast.dart:48:25)
I/flutter (32119): #2      Element.accept (package:markdown/src/ast.dart:48:41)
I/flutter (32119): #3      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:90:12)
I/flutter (32119): #4      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:107:25)
I/flutter (32119): #5      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:80:5)

```

**Comment by mit-mit** [comment]
Full details are in https://github.com/flutter/flutter_markdown/issues/3
