### ISSUE TITLE
Bug when parsing GFM extension for GitHub task lists (aka checkboxes).

### ISSUE THREAD

**Issue by isoos** [dart-lang/markdown#445]
Markdown version: 6.0.0
Original report: https://github.com/dart-lang/pub-dev/issues/5963

Reproduction input that fails:
```md
- [x] Add nodeOnTap
- [] Animations
```

```
dart run markdown --extension-set GitHubWeb graphview.md

Unhandled exception:
RangeError: Value not in range: 8
#0      _RegExpMatch.group (dart:core-patch/regexp_patch.dart:166:7)
#1      _RegExpMatch.[] (dart:core-patch/regexp_patch.dart:178:17)
#2      ListSyntax.parse (package:markdown/src/block_syntaxes/list_syntax.dart:137:47)
#3      BlockParser.parseLines (package:markdown/src/block_parser.dart:123:32)
#4      Document.parseLines (package:markdown/src/document.dart:66:44)
#5      markdownToHtml (package:markdown/src/html_renderer.dart:42:26)
#6      main (file:///home/isoos/.pub-cache/hosted/pub.dartlang.org/markdown-6.0.0/bin/markdown.dart:57:11)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

When changing `[]` (no space) to `[ ]` it works again.

**Comment by srawlins** [comment]
Ouch, good catch.

**Comment by srawlins** [comment]
I've got a fix in progress.
